// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"eagle-bank.com/internal/adapter/storage/postgres/repository/entity"
	"eagle-bank.com/internal/core/domain/model"
	"eagle-bank.com/internal/core/port"
	"sync"
)

// Ensure, that UserRepositoryMock does implement port.UserRepository.
// If this is not the case, regenerate this file with moq.
var _ port.UserRepository = &UserRepositoryMock{}

// UserRepositoryMock is a mock implementation of port.UserRepository.
//
//	func TestSomethingThatUsesUserRepository(t *testing.T) {
//
//		// make and configure a mocked port.UserRepository
//		mockedUserRepository := &UserRepositoryMock{
//			CreateUserFunc: func(newUser *model.NewUser) (*model.User, error) {
//				panic("mock out the CreateUser method")
//			},
//			GetUserByEmailFunc: func(email string) (*entity.UserDAO, error) {
//				panic("mock out the GetUserByEmail method")
//			},
//			GetUserByEmailVerificationTokenFunc: func(emailToken string) (*model.User, error) {
//				panic("mock out the GetUserByEmailVerificationToken method")
//			},
//			GetUserByIDFunc: func(id string) (*model.User, error) {
//				panic("mock out the GetUserByID method")
//			},
//			LoginFunc: func(email string, password string) (string, error) {
//				panic("mock out the Login method")
//			},
//			SetPasswordFunc: func(user *model.User, hash []byte) error {
//				panic("mock out the SetPassword method")
//			},
//			UpdateUserFunc: func(user *model.User) (*model.User, error) {
//				panic("mock out the UpdateUser method")
//			},
//			VerifyEmailFunc: func(emailToken string) error {
//				panic("mock out the VerifyEmail method")
//			},
//		}
//
//		// use mockedUserRepository in code that requires port.UserRepository
//		// and then make assertions.
//
//	}
type UserRepositoryMock struct {
	// CreateUserFunc mocks the CreateUser method.
	CreateUserFunc func(newUser *model.NewUser) (*model.User, error)

	// GetUserByEmailFunc mocks the GetUserByEmail method.
	GetUserByEmailFunc func(email string) (*entity.UserDAO, error)

	// GetUserByEmailVerificationTokenFunc mocks the GetUserByEmailVerificationToken method.
	GetUserByEmailVerificationTokenFunc func(emailToken string) (*model.User, error)

	// GetUserByIDFunc mocks the GetUserByID method.
	GetUserByIDFunc func(id string) (*model.User, error)

	// LoginFunc mocks the Login method.
	LoginFunc func(email string, password string) (string, error)

	// SetPasswordFunc mocks the SetPassword method.
	SetPasswordFunc func(user *model.User, hash []byte) error

	// UpdateUserFunc mocks the UpdateUser method.
	UpdateUserFunc func(user *model.User) (*model.User, error)

	// VerifyEmailFunc mocks the VerifyEmail method.
	VerifyEmailFunc func(emailToken string) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateUser holds details about calls to the CreateUser method.
		CreateUser []struct {
			// NewUser is the newUser argument value.
			NewUser *model.NewUser
		}
		// GetUserByEmail holds details about calls to the GetUserByEmail method.
		GetUserByEmail []struct {
			// Email is the email argument value.
			Email string
		}
		// GetUserByEmailVerificationToken holds details about calls to the GetUserByEmailVerificationToken method.
		GetUserByEmailVerificationToken []struct {
			// EmailToken is the emailToken argument value.
			EmailToken string
		}
		// GetUserByID holds details about calls to the GetUserByID method.
		GetUserByID []struct {
			// ID is the id argument value.
			ID string
		}
		// Login holds details about calls to the Login method.
		Login []struct {
			// Email is the email argument value.
			Email string
			// Password is the password argument value.
			Password string
		}
		// SetPassword holds details about calls to the SetPassword method.
		SetPassword []struct {
			// User is the user argument value.
			User *model.User
			// Hash is the hash argument value.
			Hash []byte
		}
		// UpdateUser holds details about calls to the UpdateUser method.
		UpdateUser []struct {
			// User is the user argument value.
			User *model.User
		}
		// VerifyEmail holds details about calls to the VerifyEmail method.
		VerifyEmail []struct {
			// EmailToken is the emailToken argument value.
			EmailToken string
		}
	}
	lockCreateUser                      sync.RWMutex
	lockGetUserByEmail                  sync.RWMutex
	lockGetUserByEmailVerificationToken sync.RWMutex
	lockGetUserByID                     sync.RWMutex
	lockLogin                           sync.RWMutex
	lockSetPassword                     sync.RWMutex
	lockUpdateUser                      sync.RWMutex
	lockVerifyEmail                     sync.RWMutex
}

// CreateUser calls CreateUserFunc.
func (mock *UserRepositoryMock) CreateUser(newUser *model.NewUser) (*model.User, error) {
	if mock.CreateUserFunc == nil {
		panic("UserRepositoryMock.CreateUserFunc: method is nil but UserRepository.CreateUser was just called")
	}
	callInfo := struct {
		NewUser *model.NewUser
	}{
		NewUser: newUser,
	}
	mock.lockCreateUser.Lock()
	mock.calls.CreateUser = append(mock.calls.CreateUser, callInfo)
	mock.lockCreateUser.Unlock()
	return mock.CreateUserFunc(newUser)
}

// CreateUserCalls gets all the calls that were made to CreateUser.
// Check the length with:
//
//	len(mockedUserRepository.CreateUserCalls())
func (mock *UserRepositoryMock) CreateUserCalls() []struct {
	NewUser *model.NewUser
} {
	var calls []struct {
		NewUser *model.NewUser
	}
	mock.lockCreateUser.RLock()
	calls = mock.calls.CreateUser
	mock.lockCreateUser.RUnlock()
	return calls
}

// GetUserByEmail calls GetUserByEmailFunc.
func (mock *UserRepositoryMock) GetUserByEmail(email string) (*entity.UserDAO, error) {
	if mock.GetUserByEmailFunc == nil {
		panic("UserRepositoryMock.GetUserByEmailFunc: method is nil but UserRepository.GetUserByEmail was just called")
	}
	callInfo := struct {
		Email string
	}{
		Email: email,
	}
	mock.lockGetUserByEmail.Lock()
	mock.calls.GetUserByEmail = append(mock.calls.GetUserByEmail, callInfo)
	mock.lockGetUserByEmail.Unlock()
	return mock.GetUserByEmailFunc(email)
}

// GetUserByEmailCalls gets all the calls that were made to GetUserByEmail.
// Check the length with:
//
//	len(mockedUserRepository.GetUserByEmailCalls())
func (mock *UserRepositoryMock) GetUserByEmailCalls() []struct {
	Email string
} {
	var calls []struct {
		Email string
	}
	mock.lockGetUserByEmail.RLock()
	calls = mock.calls.GetUserByEmail
	mock.lockGetUserByEmail.RUnlock()
	return calls
}

// GetUserByEmailVerificationToken calls GetUserByEmailVerificationTokenFunc.
func (mock *UserRepositoryMock) GetUserByEmailVerificationToken(emailToken string) (*model.User, error) {
	if mock.GetUserByEmailVerificationTokenFunc == nil {
		panic("UserRepositoryMock.GetUserByEmailVerificationTokenFunc: method is nil but UserRepository.GetUserByEmailVerificationToken was just called")
	}
	callInfo := struct {
		EmailToken string
	}{
		EmailToken: emailToken,
	}
	mock.lockGetUserByEmailVerificationToken.Lock()
	mock.calls.GetUserByEmailVerificationToken = append(mock.calls.GetUserByEmailVerificationToken, callInfo)
	mock.lockGetUserByEmailVerificationToken.Unlock()
	return mock.GetUserByEmailVerificationTokenFunc(emailToken)
}

// GetUserByEmailVerificationTokenCalls gets all the calls that were made to GetUserByEmailVerificationToken.
// Check the length with:
//
//	len(mockedUserRepository.GetUserByEmailVerificationTokenCalls())
func (mock *UserRepositoryMock) GetUserByEmailVerificationTokenCalls() []struct {
	EmailToken string
} {
	var calls []struct {
		EmailToken string
	}
	mock.lockGetUserByEmailVerificationToken.RLock()
	calls = mock.calls.GetUserByEmailVerificationToken
	mock.lockGetUserByEmailVerificationToken.RUnlock()
	return calls
}

// GetUserByID calls GetUserByIDFunc.
func (mock *UserRepositoryMock) GetUserByID(id string) (*model.User, error) {
	if mock.GetUserByIDFunc == nil {
		panic("UserRepositoryMock.GetUserByIDFunc: method is nil but UserRepository.GetUserByID was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	mock.lockGetUserByID.Lock()
	mock.calls.GetUserByID = append(mock.calls.GetUserByID, callInfo)
	mock.lockGetUserByID.Unlock()
	return mock.GetUserByIDFunc(id)
}

// GetUserByIDCalls gets all the calls that were made to GetUserByID.
// Check the length with:
//
//	len(mockedUserRepository.GetUserByIDCalls())
func (mock *UserRepositoryMock) GetUserByIDCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	mock.lockGetUserByID.RLock()
	calls = mock.calls.GetUserByID
	mock.lockGetUserByID.RUnlock()
	return calls
}

// Login calls LoginFunc.
func (mock *UserRepositoryMock) Login(email string, password string) (string, error) {
	if mock.LoginFunc == nil {
		panic("UserRepositoryMock.LoginFunc: method is nil but UserRepository.Login was just called")
	}
	callInfo := struct {
		Email    string
		Password string
	}{
		Email:    email,
		Password: password,
	}
	mock.lockLogin.Lock()
	mock.calls.Login = append(mock.calls.Login, callInfo)
	mock.lockLogin.Unlock()
	return mock.LoginFunc(email, password)
}

// LoginCalls gets all the calls that were made to Login.
// Check the length with:
//
//	len(mockedUserRepository.LoginCalls())
func (mock *UserRepositoryMock) LoginCalls() []struct {
	Email    string
	Password string
} {
	var calls []struct {
		Email    string
		Password string
	}
	mock.lockLogin.RLock()
	calls = mock.calls.Login
	mock.lockLogin.RUnlock()
	return calls
}

// SetPassword calls SetPasswordFunc.
func (mock *UserRepositoryMock) SetPassword(user *model.User, hash []byte) error {
	if mock.SetPasswordFunc == nil {
		panic("UserRepositoryMock.SetPasswordFunc: method is nil but UserRepository.SetPassword was just called")
	}
	callInfo := struct {
		User *model.User
		Hash []byte
	}{
		User: user,
		Hash: hash,
	}
	mock.lockSetPassword.Lock()
	mock.calls.SetPassword = append(mock.calls.SetPassword, callInfo)
	mock.lockSetPassword.Unlock()
	return mock.SetPasswordFunc(user, hash)
}

// SetPasswordCalls gets all the calls that were made to SetPassword.
// Check the length with:
//
//	len(mockedUserRepository.SetPasswordCalls())
func (mock *UserRepositoryMock) SetPasswordCalls() []struct {
	User *model.User
	Hash []byte
} {
	var calls []struct {
		User *model.User
		Hash []byte
	}
	mock.lockSetPassword.RLock()
	calls = mock.calls.SetPassword
	mock.lockSetPassword.RUnlock()
	return calls
}

// UpdateUser calls UpdateUserFunc.
func (mock *UserRepositoryMock) UpdateUser(user *model.User) (*model.User, error) {
	if mock.UpdateUserFunc == nil {
		panic("UserRepositoryMock.UpdateUserFunc: method is nil but UserRepository.UpdateUser was just called")
	}
	callInfo := struct {
		User *model.User
	}{
		User: user,
	}
	mock.lockUpdateUser.Lock()
	mock.calls.UpdateUser = append(mock.calls.UpdateUser, callInfo)
	mock.lockUpdateUser.Unlock()
	return mock.UpdateUserFunc(user)
}

// UpdateUserCalls gets all the calls that were made to UpdateUser.
// Check the length with:
//
//	len(mockedUserRepository.UpdateUserCalls())
func (mock *UserRepositoryMock) UpdateUserCalls() []struct {
	User *model.User
} {
	var calls []struct {
		User *model.User
	}
	mock.lockUpdateUser.RLock()
	calls = mock.calls.UpdateUser
	mock.lockUpdateUser.RUnlock()
	return calls
}

// VerifyEmail calls VerifyEmailFunc.
func (mock *UserRepositoryMock) VerifyEmail(emailToken string) error {
	if mock.VerifyEmailFunc == nil {
		panic("UserRepositoryMock.VerifyEmailFunc: method is nil but UserRepository.VerifyEmail was just called")
	}
	callInfo := struct {
		EmailToken string
	}{
		EmailToken: emailToken,
	}
	mock.lockVerifyEmail.Lock()
	mock.calls.VerifyEmail = append(mock.calls.VerifyEmail, callInfo)
	mock.lockVerifyEmail.Unlock()
	return mock.VerifyEmailFunc(emailToken)
}

// VerifyEmailCalls gets all the calls that were made to VerifyEmail.
// Check the length with:
//
//	len(mockedUserRepository.VerifyEmailCalls())
func (mock *UserRepositoryMock) VerifyEmailCalls() []struct {
	EmailToken string
} {
	var calls []struct {
		EmailToken string
	}
	mock.lockVerifyEmail.RLock()
	calls = mock.calls.VerifyEmail
	mock.lockVerifyEmail.RUnlock()
	return calls
}
